# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
# Dorms: Case, Atwood, East, Drinkward, Linde, North, South, West
# Rooms: Rooms random from 100-299
# Suites: Random A-Z letters

#Users

#User.create(first_name:"Stu", last_name:"Dent", email: "student@hmc.edu", is_admin: false)
#User.create(first_name:"Stu1", last_name:"Dent1", email: "student1@hmc.edu", is_admin: false)
#User.create(first_name:"Stu2", last_name:"Dent2", email: "student2@hmc.edu", is_admin: false)
#User.create(first_name:"Stu3", last_name:"Dent3", email: "student3@hmc.edu", is_admin: false)
#User.create(first_name:"Stu4", last_name:"Dent4", email: "student4@hmc.edu", is_admin: false)
#User.create(first_name:"Stu5", last_name:"Dent5", email: "student5@hmc.edu", is_admin: false)
#User.create(first_name:"Andrew", last_name:"Test", email: "wander1796@gmail.com", is_admin: false)
#User.create(first_name:"Andrew", last_name:"Test2", email: "amatherbishop@gmail.com", is_admin: false)
User.create(first_name:"Dean", last_name:"Marco", email: "mvalenzuela@g.hmc.edu", is_admin: true)
User.create(first_name:"Dean", last_name:"Karen", email: "ksandoval@g.hmc.edu", is_admin: true)
User.create(first_name:"Olivia", last_name:"Watkins", email: "owatkins@g.hmc.edu", is_admin: true)
User.create(first_name:"Gavin", last_name:"Yancey", email: "gyancey@g.hmc.edu", is_admin: true)
User.create(first_name:"Ben", last_name:"Khoury", email: "bkhoury@g.hmc.edu", is_admin: true)
User.create(first_name:"Thuy-Linh", last_name:"Le", email: "thle@g.hmc.edu", is_admin: true)
User.create(first_name:"Athena", last_name:"Li", email: "ali@g.hmc.edu", is_admin: true)
User.create(first_name:"Mia", last_name:"Taylor", email: "mtaylor@g.hmc.edu", is_admin: true)
#User.create(first_name:"Ad4", last_name:"Min4", email: "admin4@hmc.edu", is_admin: true)
#User.create(first_name:"Andrew", last_name:"Bishop", email: "abishop@g.hmc.edu", is_admin: true)



#Students
=begin
Student.create(user_id: 1, class_rank: :junior, room_draw_number: 1, number_is_last: false)
Student.create(user_id: 2, class_rank: :sophomore, room_draw_number: 2, number_is_last: false)
Student.create(user_id: 3, class_rank: :sophomore, room_draw_number: 3, number_is_last: false)
Student.create(user_id: 4, class_rank: :senior, room_draw_number: 4, number_is_last: false)
Student.create(user_id: 5, class_rank: :senior, room_draw_number: 5, number_is_last: false)
Student.create(user_id: 6, class_rank: :junior, room_draw_number: 7, number_is_last: false)
Student.create(user_id: 7, class_rank: :senior, room_draw_number: 50, number_is_last: false)
Student.create(user_id: 8, class_rank: :senior, room_draw_number: 6, number_is_last: false)
=end


#Dorms

Dorm.create([{ name: 'Atwood'}])
Dorm.create([{ name: 'Case'}])
Dorm.create([{ name: 'Drinkward'}])
Dorm.create([{ name: 'East'}])
Dorm.create([{ name: 'Linde'}])
Dorm.create([{ name: 'North'}])
Dorm.create([{ name: 'Sontag'}])
Dorm.create([{ name: 'South'}])
Dorm.create([{ name: 'West'}])

#Atwood


Suite.create(name: 'A', dorm_id: 1)
Suite.create(name: 'B', dorm_id: 1)
Suite.create(name: 'C', dorm_id: 1)
Suite.create(name: 'T', dorm_id: 1)
Suite.create(name: 'E', dorm_id: 1)

Room.create(floor: 1, capacity: 2, number: '100', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '101', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '102', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '103', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '104', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '105', dorm_id: 1)
Room.create(floor: 1, capacity: 3, number: '106', dorm_id: 1)
Room.create(floor: 1, capacity: 3, number: '107', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '108', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '109', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '110', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '111', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '112', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '113', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '114', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '115', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '116', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '117', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '118', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '119', dorm_id: 1)
Room.create(floor: 1, capacity: 3, number: '120', dorm_id: 1)
Room.create(floor: 1, capacity: 3, number: '121', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '122', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '123', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '124', dorm_id: 1)
Room.create(floor: 1, capacity: 1, number: '125', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '126', dorm_id: 1)
Room.create(floor: 1, capacity: 2, number: '127', dorm_id: 1)

Room.create(floor: 2, capacity: 2, number: '200', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '201', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '202', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '203', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '204', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '205', dorm_id: 1)
Room.create(floor: 2, capacity: 3, number: '206', dorm_id: 1)
Room.create(floor: 2, capacity: 3, number: '207', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '208', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '209', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '210', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '211', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '212', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '213', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '214', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '215', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '216', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '217', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '218', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '219', dorm_id: 1)
Room.create(floor: 2, capacity: 3, number: '220', dorm_id: 1)
Room.create(floor: 2, capacity: 3, number: '221', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '222', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '223', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '224', dorm_id: 1)
Room.create(floor: 2, capacity: 1, number: '225', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '226', dorm_id: 1)
Room.create(floor: 2, capacity: 2, number: '227', dorm_id: 1)

Room.create(floor: 3, capacity: 2, number: '300', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '301', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '302', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '303', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '304', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '305', dorm_id: 1)
Room.create(floor: 3, capacity: 3, number: '306', dorm_id: 1)
Room.create(floor: 3, capacity: 3, number: '307', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '308', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '309', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '310', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '311', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '312', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '313', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '314', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '315', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '316', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '317', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '318', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '319', dorm_id: 1)
Room.create(floor: 3, capacity: 3, number: '320', dorm_id: 1)
Room.create(floor: 3, capacity: 3, number: '321', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '322', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '323', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '324', dorm_id: 1)
Room.create(floor: 3, capacity: 1, number: '325', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '326', dorm_id: 1)
Room.create(floor: 3, capacity: 2, number: '327', dorm_id: 1)

#Case

Suite.create(name: 'A', dorm_id: 2)
Suite.create(name: 'B', dorm_id: 2)
Suite.create(name: 'C', dorm_id: 2)
Suite.create(name: 'D', dorm_id: 2)
Suite.create(name: 'E', dorm_id: 2)

Room.create(floor: 1, capacity: 2, number: '101', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '102', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '103', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '104', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '105', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '106', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '107', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '108', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '118', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '119', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '120', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '121', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '122', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '123', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '124', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '125', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '140', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '141', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '142', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '143', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '144', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '145', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '146', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '147', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '148', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '149', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '150', dorm_id: 2)
Room.create(floor: 1, capacity: 1, number: '151', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '152', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '153', dorm_id: 2)
Room.create(floor: 1, capacity: 2, number: '154', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '155', dorm_id: 2)
Room.create(floor: 1, capacity: 3, number: '156', dorm_id: 2)
Room.create(floor: 1, capacity: 4, number: '157', dorm_id: 2)

Room.create(floor: 2, capacity: 2, number: '201', dorm_id: 2)
Room.create(floor: 2, capacity: 3, number: '202', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '203', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '204', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '205', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '206', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '207', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '208', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '218', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '219', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '220', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '221', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '222', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '223', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '224', dorm_id: 2)
Room.create(floor: 2, capacity: 3, number: '225', dorm_id: 2)
Room.create(floor: 2, capacity: 3, number: '240', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '241', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '242', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '243', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '244', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '245', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '246', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '247', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '248', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '249', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '250', dorm_id: 2)
Room.create(floor: 2, capacity: 1, number: '251', dorm_id: 2)
Room.create(floor: 2, capacity: 3, number: '252', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '253', dorm_id: 2)
Room.create(floor: 2, capacity: 2, number: '254', dorm_id: 2)
Room.create(floor: 2, capacity: 3, number: '255', dorm_id: 2)
Room.create(floor: 2, capacity: 4, number: '256', dorm_id: 2)
Room.create(floor: 2, capacity: 4, number: '257', dorm_id: 2)
Room.create(floor: 2, capacity: 4, number: '258', dorm_id: 2)



############## YOU CAN ADD PULLS LIKE THIS ##############
=begin
@student1 = Student.find(1)
@room1 = Room.find(1)

@pull1 = Pull.new
@pull1.student_id = @student1.id
@pull1.room_assignments.build(
	student_id: @student1.id, 
	room_id: @room1.id, 
	assignment_type: :pulled)

@pull1.save


@student2 = Student.find(2)
@room2 = Room.find(2)

@pull2 = Pull.new
@pull2.student_id = @student2.id
@pull2.room_assignments.build(
	student_id: @student2.id, 
	room_id: @room2.id, 
	assignment_type: :pulled)

@pull2.save
=end
# #Drinkward

Suite.create(name: 'A', dorm_id: 3)
Suite.create(name: 'B', dorm_id: 3)
Suite.create(name: 'C', dorm_id: 3)
Suite.create(name: 'L', dorm_id: 3)
Suite.create(name: 'E', dorm_id: 3)

Room.create(floor: 1, capacity: 1, number: '101', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '102', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '103', dorm_id: 3)
Room.create(floor: 1, capacity: 2, number: '104', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '105', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '106', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '107', dorm_id: 3)
Room.create(floor: 1, capacity: 2, number: '108', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '109', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '110', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '111', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '112', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '113', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '114', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '115', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '116', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '117', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '118', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '119', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '120', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '120.1', dorm_id: 3)
Room.create(floor: 1, capacity: 2, number: '122.4', dorm_id: 3)
Room.create(floor: 1, capacity: 2, number: '122.3', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '123.3', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '123.4', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '123.5', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '123.6', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '124.6', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '124.5', dorm_id: 3)
Room.create(floor: 1, capacity: 1, number: '124.4', dorm_id: 3)
Room.create(floor: 1, capacity: 3, number: '124.3', dorm_id: 3)

Room.create(floor: 2, capacity: 1, number: '201', dorm_id: 3)
Room.create(floor: 2, capacity: 2, number: '202', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '203', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '204', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '205', dorm_id: 3)
Room.create(floor: 2, capacity: 2, number: '206', dorm_id: 3)
Room.create(floor: 2, capacity: 2, number: '207', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '208', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '209', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '210', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '211', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '212', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '213', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '214', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '215', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '216', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '217', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '218', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '219', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '220', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '221.3', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '221.4', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '221.5', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '221.6', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '222.3', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '222.4', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '222.5', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '223.3', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '223.4', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '223.5', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '223.6', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '224.6', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '224.5', dorm_id: 3)
Room.create(floor: 2, capacity: 1, number: '224.4', dorm_id: 3)
Room.create(floor: 2, capacity: 3, number: '224.3', dorm_id: 3)

Room.create(floor: 3, capacity: 1, number: '301', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '302', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '303', dorm_id: 3)
Room.create(floor: 3, capacity: 2, number: '304', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '305', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '306', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '307', dorm_id: 3)
Room.create(floor: 3, capacity: 2, number: '308', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '309', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '310', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '311', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '312', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '313', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '314', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '315', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '316', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '317', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '318', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '319', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '320', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '320.1', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '321.3', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '321.4', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '321.5', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '321.6', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '322.3', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '322.4', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '322.5', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '323.3', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '323.4', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '323.5', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '323.6', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '324.6', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '324.5', dorm_id: 3)
Room.create(floor: 3, capacity: 1, number: '324.4', dorm_id: 3)
Room.create(floor: 3, capacity: 3, number: '324.3', dorm_id: 3)


# #East

# Suite.create(name: 'A', dorm_id: 3)
# Suite.create(name: 'B', dorm_id: 3)
# Suite.create(name: 'C', dorm_id: 3)
# Suite.create(name: 'M', dorm_id: 3)
# Suite.create(name: 'E', dorm_id: 3)

Room.create(floor: 1, capacity: 2, number: '101', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '102', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '103', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '104', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '105', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '106', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '107', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '108', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '109', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '110', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '111', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '112', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '113', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '114', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '115', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '116', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '119', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '120', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '121', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '122', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '123', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '124', dorm_id: 4)
Room.create(floor: 1, capacity: 2, number: '125', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '126', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '127', dorm_id: 4)
Room.create(floor: 1, capacity: 1, number: '128', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '151', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '152', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '153', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '154', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '155', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '156', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '157', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '158', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '159', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '160', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '161', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '162', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '163', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '164', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '165', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '166', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '169', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '170', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '171', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '172', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '173', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '174', dorm_id: 4)
Room.create(floor: 2, capacity: 2, number: '175', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '176', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '177', dorm_id: 4)
Room.create(floor: 2, capacity: 1, number: '178', dorm_id: 4)


# #Linde

Suite.create(name: 'A', dorm_id: 5)
Suite.create(name: 'B', dorm_id: 5)
Suite.create(name: 'C', dorm_id: 5)
Suite.create(name: 'S', dorm_id: 5)
Suite.create(name: 'E', dorm_id: 5)

Room.create(floor: 1, capacity: 1, number: '101', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '102', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '103', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '105', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '107', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '110', dorm_id: 5)
Room.create(floor: 1, capacity: 3, number: '111', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '112', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '113', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '116', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '117', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '129', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '130', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '131', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '132', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '135', dorm_id: 5)
Room.create(floor: 1, capacity: 3, number: '136', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '138', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '140', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '141', dorm_id: 5)
Room.create(floor: 1, capacity: 2, number: '144', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '145', dorm_id: 5)
Room.create(floor: 1, capacity: 1, number: '146', dorm_id: 5)

Room.create(floor: 2, capacity: 1, number: '201', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '202', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '203', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '204', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '207', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '208', dorm_id: 5)
Room.create(floor: 2, capacity: 3, number: '211', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '212', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '213', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '216', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '217', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '219', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '222', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '227', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '229', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '230', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '231', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '232', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '233', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '236', dorm_id: 5)
Room.create(floor: 2, capacity: 3, number: '237', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '239', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '240', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '243', dorm_id: 5)
Room.create(floor: 2, capacity: 2, number: '244', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '246', dorm_id: 5)
Room.create(floor: 2, capacity: 1, number: '247', dorm_id: 5)

# #North

Suite.create(name: 'A', dorm_id: 6)
Suite.create(name: 'B', dorm_id: 6)
Suite.create(name: 'H', dorm_id: 6)
Suite.create(name: 'D', dorm_id: 6)
Suite.create(name: 'E', dorm_id: 6)

Room.create(floor: 1, capacity: 2, number: '201', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '202', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '203', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '204', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '205', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '206', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '207', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '208', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '209', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '210', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '211', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '212', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '213', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '214', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '215', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '216', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '219', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '220', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '221', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '222', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '223', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '224', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '225', dorm_id: 6)
Room.create(floor: 1, capacity: 2, number: '226', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '227', dorm_id: 6)
Room.create(floor: 1, capacity: 1, number: '228', dorm_id: 6)

Room.create(floor: 2, capacity: 2, number: '251', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '252', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '253', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '254', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '255', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '256', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '257', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '258', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '259', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '260', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '261', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '262', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '262', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '263', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '264', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '265', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '266', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '269', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '270', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '271', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '272', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '273', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '274', dorm_id: 6)
Room.create(floor: 2, capacity: 2, number: '275', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '276', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '277', dorm_id: 6)
Room.create(floor: 2, capacity: 1, number: '278', dorm_id: 6)

# #South

# Suite.create(name: 'A', dorm_id: 7)
# Suite.create(name: 'B', dorm_id: 7)
# Suite.create(name: 'C', dorm_id: 7)
# Suite.create(name: 'L', dorm_id: 7)
# Suite.create(name: 'E', dorm_id: 7)

Room.create(floor: 1, capacity: 1, number: '307.1', dorm_id: 8, suite_id: 307)
Room.create(floor: 1, capacity: 1, number: '307.2', dorm_id: 8, suite_id: 307)
Room.create(floor: 1, capacity: 1, number: '307.3', dorm_id: 8, suite_id: 307)
Room.create(floor: 1, capacity: 1, number: '307.4', dorm_id: 8, suite_id: 307)
Room.create(floor: 1, capacity: 1, number: '305.1', dorm_id: 8, suite_id: 305)
Room.create(floor: 1, capacity: 1, number: '305.2', dorm_id: 8, suite_id: 305)
Room.create(floor: 1, capacity: 1, number: '305.3', dorm_id: 8, suite_id: 305)
Room.create(floor: 1, capacity: 1, number: '303.1', dorm_id: 8, suite_id: 303)
Room.create(floor: 1, capacity: 1, number: '303.2', dorm_id: 8, suite_id: 303)
Room.create(floor: 1, capacity: 1, number: '303.3', dorm_id: 8, suite_id: 303)
Room.create(floor: 1, capacity: 1, number: '301.1', dorm_id: 8, suite_id: 301)
Room.create(floor: 1, capacity: 1, number: '301.2', dorm_id: 8, suite_id: 301)
Room.create(floor: 1, capacity: 1, number: '301.3', dorm_id: 8, suite_id: 301)
Room.create(floor: 1, capacity: 1, number: '301.4', dorm_id: 8, suite_id: 301)
Room.create(floor: 1, capacity: 1, number: '308.1', dorm_id: 8, suite_id: 308)
Room.create(floor: 1, capacity: 1, number: '308.2', dorm_id: 8, suite_id: 308)
Room.create(floor: 1, capacity: 1, number: '308.3', dorm_id: 8, suite_id: 308)
Room.create(floor: 1, capacity: 1, number: '308.4', dorm_id: 8, suite_id: 308)
Room.create(floor: 1, capacity: 1, number: '306.1', dorm_id: 8, suite_id: 306)
Room.create(floor: 1, capacity: 1, number: '306.2', dorm_id: 8, suite_id: 306)
Room.create(floor: 1, capacity: 1, number: '306.3', dorm_id: 8, suite_id: 306)
Room.create(floor: 1, capacity: 1, number: '304.1', dorm_id: 8, suite_id: 304)
Room.create(floor: 1, capacity: 1, number: '304.2', dorm_id: 8, suite_id: 304)
Room.create(floor: 1, capacity: 1, number: '304.3', dorm_id: 8, suite_id: 304)
Room.create(floor: 1, capacity: 1, number: '302.1', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '302.2', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '302.3', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '302.4', dorm_id: 8, suite_id: 302)
# single rooms
Room.create(floor: 1, capacity: 1, number: '309', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '311', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '312', dorm_id: 8, suite_id: 302)
Room.create(floor: 1, capacity: 1, number: '310', dorm_id: 8, suite_id: 302)
# floor 2
# suites
Room.create(floor: 2, capacity: 1, number: '357.1', dorm_id: 8, suite_id: 357)
Room.create(floor: 2, capacity: 1, number: '357.2', dorm_id: 8, suite_id: 357)
Room.create(floor: 2, capacity: 1, number: '357.3', dorm_id: 8, suite_id: 357)
Room.create(floor: 2, capacity: 1, number: '357.4', dorm_id: 8, suite_id: 357)
Room.create(floor: 2, capacity: 1, number: '355.1', dorm_id: 8, suite_id: 355)
Room.create(floor: 2, capacity: 1, number: '355.2', dorm_id: 8, suite_id: 355)
Room.create(floor: 2, capacity: 1, number: '355.3', dorm_id: 8, suite_id: 355)
Room.create(floor: 2, capacity: 1, number: '353.1', dorm_id: 8, suite_id: 353)
Room.create(floor: 2, capacity: 1, number: '353.2', dorm_id: 8, suite_id: 353)
Room.create(floor: 2, capacity: 1, number: '353.3', dorm_id: 8, suite_id: 353)
Room.create(floor: 2, capacity: 1, number: '351.1', dorm_id: 8, suite_id: 351)
Room.create(floor: 2, capacity: 1, number: '351.2', dorm_id: 8, suite_id: 351)
Room.create(floor: 2, capacity: 1, number: '351.3', dorm_id: 8, suite_id: 351)
Room.create(floor: 2, capacity: 1, number: '351.4', dorm_id: 8, suite_id: 351)
Room.create(floor: 2, capacity: 1, number: '358.1', dorm_id: 8, suite_id: 358)
Room.create(floor: 2, capacity: 1, number: '358.2', dorm_id: 8, suite_id: 358)
Room.create(floor: 2, capacity: 1, number: '358.3', dorm_id: 8, suite_id: 358)
Room.create(floor: 2, capacity: 1, number: '358.4', dorm_id: 8, suite_id: 358)
Room.create(floor: 2, capacity: 1, number: '356.1', dorm_id: 8, suite_id: 356)
Room.create(floor: 2, capacity: 1, number: '356.2', dorm_id: 8, suite_id: 356)
Room.create(floor: 2, capacity: 1, number: '356.3', dorm_id: 8, suite_id: 356)
Room.create(floor: 2, capacity: 1, number: '354.1', dorm_id: 8, suite_id: 354)
Room.create(floor: 2, capacity: 1, number: '354.2', dorm_id: 8, suite_id: 354)
Room.create(floor: 2, capacity: 1, number: '354.3', dorm_id: 8, suite_id: 354)
Room.create(floor: 2, capacity: 1, number: '352.1', dorm_id: 8, suite_id: 352)
Room.create(floor: 2, capacity: 1, number: '352.2', dorm_id: 8, suite_id: 352)
Room.create(floor: 2, capacity: 1, number: '352.3', dorm_id: 8, suite_id: 352)
Room.create(floor: 2, capacity: 1, number: '352.4', dorm_id: 8, suite_id: 352)
# single rooms
Room.create(floor: 2, capacity: 1, number: '359', dorm_id: 8, suite_id: 359)
Room.create(floor: 2, capacity: 1, number: '360', dorm_id: 8, suite_id: 360)
Room.create(floor: 2, capacity: 1, number: '361', dorm_id: 8, suite_id: 361)
Room.create(floor: 2, capacity: 1, number: '362', dorm_id: 8, suite_id: 362)
Room.create(floor: 2, capacity: 1, number: '363', dorm_id: 8, suite_id: 363)
Room.create(floor: 2, capacity: 1, number: '364', dorm_id: 8, suite_id: 364)
Room.create(floor: 2, capacity: 1, number: '365', dorm_id: 8, suite_id: 365)
Room.create(floor: 2, capacity: 1, number: '366', dorm_id: 8, suite_id: 366)

# #West

Suite.create(name: 'A', dorm_id: 8)
Suite.create(name: 'F', dorm_id: 8)
Suite.create(name: 'C', dorm_id: 8)
Suite.create(name: 'D', dorm_id: 8)
Suite.create(name: 'E', dorm_id: 8)

# first floor
Room.create(floor: 1, capacity: 2, number: '401', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '402', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '403', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '404', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '405', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '406', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '407', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '408', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '409', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '410', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '411', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '412', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '413', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '414', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '415', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '416', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '422', dorm_id: 9)
Room.create(floor: 1, capacity: 2, number: '426', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '420', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '424', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '428', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '427', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '423', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '419', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '425', dorm_id: 9)
Room.create(floor: 1, capacity: 1, number: '421', dorm_id: 9)
# second floor
Room.create(floor: 2, capacity: 2, number: '451', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '452', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '453', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '454', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '455', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '456', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '457', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '458', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '459', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '460', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '461', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '462', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '463', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '464', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '465', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '466', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '472', dorm_id: 9)
Room.create(floor: 2, capacity: 2, number: '476', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '470', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '474', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '478', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '477', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '473', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '469', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '475', dorm_id: 9)
Room.create(floor: 2, capacity: 1, number: '471', dorm_id: 9)

# #Sontag

Suite.create(name: 'A', dorm_id: 7)
Suite.create(name: 'F', dorm_id: 7)
Suite.create(name: 'C', dorm_id: 7)
Suite.create(name: 'D', dorm_id: 7)
Suite.create(name: 'E', dorm_id: 7)

Room.create(floor: 1, capacity: 1, number: '101.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '101.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '101.3', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '101.4', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '102.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '102.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '102.3', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '102.4', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '103.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '103.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '103.3', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '103.4', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '104', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '105.4', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '105.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '105.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '106.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '106.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '106.3', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '106.4', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '107.1', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '107.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '107.3', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '107.4', dorm_id: 7)
Room.create(floor: 1, capacity: 2, number: '108.4', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '108.3', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '108.2', dorm_id: 7)
Room.create(floor: 1, capacity: 1, number: '108.1', dorm_id: 7)

Room.create(floor: 2, capacity: 1, number: '201.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '201.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '201.3', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '201.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '202.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '202.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '202.3', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '202.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '203.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '203.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '203.3', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '203.4', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '204.1', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '204.2', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '204.4', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '205.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '205.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '205.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '206.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '206.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '206.3', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '206.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '207.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '207.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '207.3', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '207.4', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '208.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '208.3', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '208.2', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '208.1', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '209.1', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '209.4', dorm_id: 7)
Room.create(floor: 2, capacity: 1, number: '210.1', dorm_id: 7)
Room.create(floor: 2, capacity: 2, number: '210.4', dorm_id: 7)

